### PR TITLE
Add `swarm agents` CLI subcommand to list registered agent types

### PR DESCRIPTION
**Pull request by adv0r**
> **Dear maintainer** — this PR has a permanent home with methodology + [opt-out](https://github.com/adv0r/tokens-for-good/blob/main/MAINTAINER_REMOVAL.md) at [tokens-for-good](https://github.com/adv0r/tokens-for-good). A one-line "no thanks" → auto-close + blacklist. Sorry for the notification this edit caused.
>
> ---

AI-assisted via Cursor (Claude Opus 4.7).
Personal token-burn initiative: contributing OSS work using leftover Cursor credits before subscription renewal.

Closes #352.

## What changed

Adds a new `agents` subcommand to `python -m swarm`:

- Discovers `BaseAgent` subclasses via `swarm.agents.__all__` (no hard-coded list), so the list stays in sync with the package automatically.
- Default output: alphabetical table of `AGENT  DESCRIPTION`, where the description is the first line of each class docstring.
- `-v / --verbose`: prints the fully-qualified module path and the complete docstring per agent.
- Excludes the abstract `BaseAgent` itself and non-agent symbols (`Action`, `ActionType`, `Observation`, `MemoryConfig`, `AttackStrategy`, `ObfuscationStrategy`).

Sample output:

\`\`\`
$ python -m swarm agents | head
AGENT                    DESCRIPTION
-----------------------  -----------
AdaptiveAdversary        Adaptive adversary that learns to evade governance.
AdaptiveAgent            Agent that learns from outcomes and adapts its acceptance strategy.
AdversarialAgent         Adversarial agent that actively works against the ecosystem.
...
\`\`\`

\`\`\`
$ python -m swarm agents -v | head -5
AdaptiveAdversary
  module: swarm.agents.adaptive_adversary
  Adaptive adversary that learns to evade governance.

  Features:
\`\`\`

## How verified

- \`python -m swarm agents\` and \`python -m swarm agents -v\` both render correctly (29 agent types listed; \`BaseAgent\` is correctly excluded).
- \`python -m swarm agents --help\` shows expected usage.
- New tests in \`tests/test_cli.py::TestAgentsSubcommand\` (3 cases) all pass:
  - lists known agent types (\`HonestAgent\`, \`AdversarialAgent\`),
  - excludes \`BaseAgent\`,
  - verbose mode includes module paths and multi-line docstrings.
- Full \`pytest tests/test_cli.py\` is green except for one pre-existing failure (\`test_run_export_json\`) due to a missing \`matplotlib\` optional dependency — same import-time failure tracked in #350 / addressed in the companion PR for pyyaml; unrelated to this change.
- \`ruff check swarm/__main__.py tests/test_cli.py\` is clean.

## Notes

Per \`AGENTS.md\` this was prepared by Claude Opus 4.7 (Cursor) with @adv0r as the human in the loop — happy to add a CONTRIBUTORS.md credit if the maintainers prefer the AI agent to be listed separately.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by rsavitt** [comment]
Thanks for this! One real blocker before it can merge:

**`type-check` fails** at `swarm/__main__.py:446`:
\`\`\`
error: Incompatible types in assignment (expression has type "str | None", variable has type "str")  [assignment]
\`\`\`
The repo runs mypy with `warn_return_any` in `quality-gate`, so this needs a fix — likely a narrowing/guard or an explicit annotation on the assignment at line 446.

The other CI reds are **not** on you:
- `Vercel – swarm` → external deploy-auth, non-blocking.
- `test_orchestrator.py::test_run_multi_agent_simulation` and `test_compare_nonexistent_run_404` → flaky/pre-existing under xdist parallelism; both pass on `main` and locally. They'll clear on a rerun once the type error is fixed.

Once line 446 is sorted and you push, CI should go green. Happy to take another look then.

**Review by rsavitt — COMMENTED** [review]
.

**Comment by rsavitt** [comment]
Thanks for this! Pushed a small fix for the one real blocker — the `type-check` failure at `swarm/__main__.py:446`.

**Root cause:** `inspect.getdoc()` returns `str | None`. The verbose branch at line 434 already narrows `doc` to `str` via `or "(no docstring)"`, so reassigning the raw `str | None` at line 446 tripped mypy's `[assignment]` check (which `quality-gate` enforces). Fixed by mirroring the line-434 pattern:

```python
doc = inspect.getdoc(cls) or "(no docstring)"
first_line = doc.splitlines()[0]
```

Output is unchanged (empty/whitespace docstrings still render the placeholder, no `IndexError`). `mypy swarm/__main__.py` is clean locally.

The other CI reds aren't on you:
- **Vercel – swarm** → external deploy-auth ("Authorization required to deploy"), non-blocking.
- **`test_run_multi_agent_simulation`** and **`test_compare_nonexistent_run_404`** → pre-existing flakiness under xdist; both live in files this PR doesn't touch (`test_orchestrator.py` / `test_agent_api.py`), and `test (3.11)` passed while 3.10/3.12 flaked. They should clear on rerun now that type-check is fixed.

CI should go green on the rerun. 🎈

**Comment by adv0r** [comment]
Thanks for the review and merge.
